hrservicecenter/force-app/main/default/objects/OnboardingTask__c/OnboardingTask__c.object-meta.xml
<CustomObject>
    <description>This entity represents various onboarding tasks an HR can create for their employees.</description>
    <label>Onboarding Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/FlowAPIName__c.field-meta.xml
<CustomField>
    <fullName>FlowAPIName__c</fullName>
    <description>API name of the flow associated with this task. All onboarding tasks must reference a flow.</description>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/StartDayOffset__c.field-meta.xml
<CustomField>
    <fullName>StartDayOffset__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This indicates when the employee should begin this onboarding task relative to their start date.</description>
    <label>Start Day Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/Task/recordTypes/OnboardingTask.recordType-meta.xml
<RecordType>
    <fullName>OnboardingTask</fullName>
    <active>true</active>
    <label>Onboarding Task</label>
</RecordType>

hrservicecenter/force-app/main/default/classes/tests/OnboardingChecklistUtilTest.cls
/**
 * @author  Kunal Parmani
 * @date    5/17/21
 * @description Test Util class for OnboardingChecklist.
 * @log
 * -----------------------------------------------------------------------------
 * Date        Developer            Description
 * -----------------------------------------------------------------------------
 * 4/16/21     kunal parmani
 * 5/27/21     rkolasinski          W-000103 - Updates related to new data model.
 */
@IsTest
public class OnboardingChecklistUtilTest {
    public static List<String> getFlowNames() {
        List<String> flowNameList = new List<String>();
        flowNameList.add('Benefits 401K');
        flowNameList.add('Direct Deposit');
        flowNameList.add('Disability Disclosure');
        flowNameList.add('Sign Non-Disclosure Agreement');
        flowNameList.add('Verify Identity');
        flowNameList.add('I9 - Employment Eligibility Verification');
        flowNameList.add('Benefits Review');

        return flowNameList;
    }

    public static List<OnboardingTask__c> createOnboardingTasks(
        List<String> flowNameList
    ) {
        List<OnboardingTask__c> onboardingTasks = new List<OnboardingTask__c>();
        for (String flowName : flowNameList) {
            OnboardingTask__c onBoardOption = new OnboardingTask__c();
            onBoardOption.StartDayOffset__c = 7;
            onBoardOption.FlowAPIName__c = flowName;
            onBoardOption.Name = flowName + ' Label';
            onBoardOption.Description__c =
                'Description placeholder for ' + flowName;
            onboardingTasks.add(onBoardOption);
        }

        insert onboardingTasks;
        return onboardingTasks;
    }

    public static List<Task> createTasks(
        List<OnboardingTask__c> onboardingTasks,
        Id ownerId
    ) {
        List<Task> taskList = new List<Task>();
        Id onboardingTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName()
            .get(OnboardingChecklist.ONBOARDING_TASK_RECORD_TYPE_DEVELOPER_NAME)
            .getRecordTypeId();

        for (OnboardingTask__c onboardingTask : onboardingTasks) {
            Task employeeTask = new Task();
            employeeTask.Status = 'New';
            employeeTask.WhatId = onboardingTask.Id;
            employeeTask.RecordTypeId = onboardingTaskRecordTypeId;
            employeeTask.OwnerId = ownerId;
            taskList.add(employeeTask);
        }

        insert taskList;
        return taskList;
    }
}