hrservicecenter/force-app/main/default/objects/OnboardingTask__c/OnboardingTask__c.object-meta.xml
<CustomObject>
    <description>This entity represents various onboarding tasks an HR can create for their employees.</description>
    <label>Onboarding Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/FlowAPIName__c.field-meta.xml
<CustomField>
    <fullName>FlowAPIName__c</fullName>
    <description>API name of the flow associated with this task. All onboarding tasks must reference a flow.</description>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/StartDayOffset__c.field-meta.xml
<CustomField>
    <fullName>StartDayOffset__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This indicates when the employee should begin this onboarding task relative to their start date.</description>
    <label>Start Day Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/OnboardingTemplate__c.object-meta.xml
<CustomObject>
    <description>Custom object that enables an HR agent to create a list of tasks that will help a new employee onboard into the organization.</description>
    <label>Onboarding Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the template.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/OnboardingTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Custom object that represents onboarding tasks that can be associated with a template.</description>
    <label>Onboarding Template Task</label>
    <nameField>
        <displayFormat>OTT-{0000}</displayFormat>
        <label>Template Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTask__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Onboarding Task that is linked to the template</description>
    <label>Onboarding Task</label>
    <referenceTo>OnboardingTask__c</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTemplate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTemplate__c</fullName>
    <description>Parent Template record Id.</description>
    <label>Onboarding Template</label>
    <referenceTo>OnboardingTemplate__c</referenceTo>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hrservicecenter/force-app/main/default/classes/tests/TestDataFactory_Hrsc.cls
/**
 * @author  rkolasinski
 * @date    4/16/21
 * @description Test data factory class.
 * @log
 * -----------------------------------------------------------------------------
 * Date        Developer            Description
 * -----------------------------------------------------------------------------
 * 4/16/21     rkolasinski          US-1 - created.
 */

@IsTest
public class TestDataFactory_Hrsc {
    public static User createSysAdminUser(String email) {
        Profile p = [
            SELECT Id, Name
            FROM Profile
            WHERE Name = 'System Administrator'
            LIMIT 1
        ];

        User u = new User(
            LastName = 'TestAdmin',
            Alias = 'utUser',
            Username = email + '.test',
            Email = email,
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            UserPermissionsKnowledgeUser = true
        );

        return u;
    }

    public static Account createTestAccount(String testName) {
        Account a = new Account(Name = testName);
        return a;
    }

    public static Contact createTestContact(
        String firstName,
        String lastName,
        String email,
        String phone
    ) {
        Contact c = new Contact(
            FirstName = firstName,
            LastName = lastName,
            Email = email,
            Phone = phone
        );
        return c;
    }

    public static User createExternalUser(
        Id contactId,
        String email,
        String profileName
    ) {
        User u = new User();
        u.LastName = 'External';
        u.Alias = 'utUser';
        u.LastName = 'User';
        u.Username = email + '.test';
        // u.ContactId = contactId;
        u.Email = email;
        Profile profile = [SELECT Id FROM Profile WHERE Name = :profileName];
        u.ProfileId = profile.Id;
        u.TimeZoneSidKey = 'America/New_York';
        u.LocaleSidKey = 'en_US';
        u.LanguageLocaleKey = 'en_US';
        u.EmailEncodingKey = 'ISO-8859-1';
        return u;
    }

    public static Employee createTestEmployee(
        String firstName,
        String lastName,
        String email,
        String employeeNumber,
        String employeeStatus,
        Datetime statusAsOf,
        String workerType,
        Id userId,
        Id managerId,
        Id ownerId
    ) {
        Employee e = new Employee(
            FirstName = firstName,
            LastName = lastName,
            Email = email,
            EmployeeNumber = employeeNumber,
            EmployeeStatus = employeeStatus,
            StatusAsOf = statusAsOf,
            WorkerType = workerType,
            UserId = userId,
            ManagerId = managerId,
            OwnerId = ownerId
        );
        insert e;
        return e;
    }

    public static List<String> getFlowNames() {
        List<String> flowNameList = new List<String>();
        flowNameList.add('Benefits 401K');
        flowNameList.add('Direct Deposit');
        flowNameList.add('Disability Disclosure');
        flowNameList.add('Sign Non-Disclosure Agreement');
        flowNameList.add('Verify Identity');
        flowNameList.add('I9 - Employment Eligibility Verification');
        flowNameList.add('Benefits Review');

        return flowNameList;
    }

    public static OnboardingTemplate__c createOnboardingTemplates(
        String templateName
    ) {
        OnboardingTemplate__c oBTemplate = new OnboardingTemplate__c();
        oBTemplate.Name = templateName;
        oBTemplate.Description__c = 'Some Onboarding Template Description here!!';
        oBTemplate.IsActive__c = true;

        return oBTemplate;
    }

    public static List<OnboardingTask__c> createOnboardingTask(
        List<String> taskNameList
    ) {
        List<OnboardingTask__c> oBTaskList = new List<OnboardingTask__c>();

        for (String tsk : taskNameList) {
            OnboardingTask__c oBTask = new OnboardingTask__c();
            oBTask.Description__c = 'Some Onboarding Task Description here!!';
            oBTask.FlowAPIName__c = tsk;
            oBTask.StartDayOffset__c = 7;
            oBTask.name = tsk;
            oBTaskList.add(oBTask);
        }

        return oBTaskList;
    }

    public static List<OnboardingTemplateTask__c> createOnboardingTemplateTask(
        OnboardingTemplate__c oBTemplate,
        List<OnboardingTask__c> oBTaskList
    ) {
        List<OnboardingTemplateTask__c> oBTemplateTaskList = new List<OnboardingTemplateTask__c>();

        for (OnboardingTask__c oBTask : oBTaskList) {
            OnboardingTemplateTask__c oBTemplateTask = new OnboardingTemplateTask__c();
            oBTemplateTask.OnboardingTask__c = oBTask.Id;
            oBTemplateTask.OnboardingTemplate__c = oBTemplate.Id;
            oBTemplateTaskList.add(oBTemplateTask);
        }

        return oBTemplateTaskList;
    }
}