hrservicecenter/force-app/main/default/objects/OnboardingTask__c/OnboardingTask__c.object-meta.xml
<CustomObject>
    <description>This entity represents various onboarding tasks an HR can create for their employees.</description>
    <label>Onboarding Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/FlowAPIName__c.field-meta.xml
<CustomField>
    <fullName>FlowAPIName__c</fullName>
    <description>API name of the flow associated with this task. All onboarding tasks must reference a flow.</description>
    <label>Flow API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/StartDayOffset__c.field-meta.xml
<CustomField>
    <fullName>StartDayOffset__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This indicates when the employee should begin this onboarding task relative to their start date.</description>
    <label>Start Day Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/OnboardingTemplate__c.object-meta.xml
<CustomObject>
    <description>Custom object that enables an HR agent to create a list of tasks that will help a new employee onboard into the organization.</description>
    <label>Onboarding Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the template.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/OnboardingTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Custom object that represents onboarding tasks that can be associated with a template.</description>
    <label>Onboarding Template Task</label>
    <nameField>
        <displayFormat>OTT-{0000}</displayFormat>
        <label>Template Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTask__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Onboarding Task that is linked to the template</description>
    <label>Onboarding Task</label>
    <referenceTo>OnboardingTask__c</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTemplate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTemplate__c</fullName>
    <description>Parent Template record Id.</description>
    <label>Onboarding Template</label>
    <referenceTo>OnboardingTemplate__c</referenceTo>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/Task/recordTypes/OnboardingTask.recordType-meta.xml
<RecordType>
    <fullName>OnboardingTask</fullName>
    <active>true</active>
    <label>Onboarding Task</label>
</RecordType>

hrservicecenter/force-app/main/default/classes/tests/CreateOnboardingTasksTest.cls
/**
 * @author  Kunal Parmani
 * @date    6/03/21
 * @description Test class for CreateOnboardingTasks.
 * @log
 * -----------------------------------------------------------------------------
 * Date        Developer
 * -----------------------------------------------------------------------------
 * 6/03/21     kunal parmani
 */
@isTest
public with sharing class CreateOnboardingTasksTest {
    public static final String TEST_EMAIL_EMPLOYEE = 'employee@unittest.com';
    public static final String TEST_EMAIL_EMPLOYEE_WITHOUT_USER = 'employeeNoUser@unittest.com';
    private static final String ONBOARDING_TASK_RECORD_TYPE_DEVELOPER_NAME = 'OnboardingTask';

    /**
     * Prepares the data to test the CreateOnboardingTasks class.
     * Creates Account,Contact,Users,Employee records.
     */
    @testSetup
    public static void testData() {
        User sysAdmin = TestDataFactory_Hrsc.createSysAdminUser(
            'sysadmin@unittest.com'
        );

        System.runAs(sysAdmin) {
            Account testAdmin = TestDataFactory_Hrsc.createTestAccount(
                'Test Name'
            );
            insert testAdmin;

            Contact testContact = TestDataFactory_Hrsc.createTestContact(
                'Test First',
                'Test Last',
                TEST_EMAIL_EMPLOYEE,
                '9999999991'
            );
            testContact.AccountId = testAdmin.Id;
            insert testContact;

            User testHiringManager = TestDataFactory_Hrsc.createExternalUser(
                null,
                TEST_EMAIL_EMPLOYEE,
                'Standard Platform User'
            );
            insert testHiringManager;

            Employee manager = TestDataFactory_Hrsc.createTestEmployee(
                'Test',
                'Manager',
                TEST_EMAIL_EMPLOYEE,
                '0001',
                'Active',
                Datetime.newInstance(2021, 4, 10),
                'Employee',
                testHiringManager.Id,
                null,
                testHiringManager.Id
            );

            Employee employeeWithoutUser = TestDataFactory_Hrsc.createTestEmployee(
                'Test',
                'NoUser',
                TEST_EMAIL_EMPLOYEE_WITHOUT_USER,
                '0002',
                'Active',
                Datetime.newInstance(2021, 4, 10),
                'Employee',
                null,
                null,
                UserInfo.getUserId()
            );

            OnboardingTemplate__c oBTemplate = TestDataFactory_Hrsc.createOnboardingTemplates(
                'Basic Onboarding'
            );
            insert oBTemplate;

            List<String> flowNameList = TestDataFactory_Hrsc.getFlowNames();
            List<OnboardingTask__c> oBTaskList = TestDataFactory_Hrsc.createOnboardingTask(
                flowNameList
            );
            insert oBTaskList;

            List<OnboardingTemplateTask__c> oBTemplateTaskList = TestDataFactory_Hrsc.createOnboardingTemplateTask(
                oBTemplate,
                oBTaskList
            );
            insert oBTemplateTaskList;
        }
    }

    /**
     * Test Method to test the createTasks() method
     */
    @isTest
    public static void testcreateTasksForEmployeeWithUser() {
        Employee testEmployee = [
            SELECT id, EmployeeNumber, UserId, Name, StatusAsOf
            FROM Employee
            WHERE Email = :TEST_EMAIL_EMPLOYEE
        ];
        Id onboardingTaskRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName()
            .get(ONBOARDING_TASK_RECORD_TYPE_DEVELOPER_NAME)
            .getRecordTypeId();

        List<CreateOnboardingTasks.RequestInput> requestInputs = new List<CreateOnboardingTasks.RequestInput>();
        CreateOnboardingTasks.RequestInput req = new CreateOnboardingTasks.RequestInput();
        req.selectedTemplates = 'Basic Onboarding';
        req.UserID = testEmployee.UserId;
        requestInputs.add(req);

        Test.startTest();
        List<CreateOnboardingTasks.RequestOutput> requestOutputs = CreateOnboardingTasks.createTasks(
            requestInputs
        );
        Test.stopTest();

        System.assert(requestOutputs[0].isSuccess);
        System.assert(requestOutputs[0].total_Onboarding_Task > 0);

        List<Task> tasks = [
            SELECT Id, WhatId, OwnerId, Status, ActivityDate
            FROM Task
            WHERE
                OwnerId = :testEmployee.UserId
                AND RecordTypeId = :onboardingTaskRecordTypeId
        ];

        System.assertNotEquals(0, tasks.size(), 'Tasks list is not empty');

        Set<Id> onboardingTaskIds = new Set<Id>();
        for (Task t : tasks) {
            onboardingTaskIds.add(t.WhatId);
        }

        List<OnboardingTask__c> onboardingTasks = [
            SELECT Id, Name, Description__c, FlowAPIName__c, StartDayOffset__c
            FROM OnboardingTask__c
            WHERE Id IN :onboardingTaskIds
        ];

        for (Task t : tasks) {
            for (OnboardingTask__c onboardingTask : onboardingTasks) {
                if (t.WhatId == onboardingTask.Id) {
                    System.assertEquals(
                        testEmployee.StatusAsOf.date()
                            .addDays(
                                Integer.valueOf(
                                    onboardingTask.StartDayOffset__c
                                )
                            ),
                        t.ActivityDate,
                        'Activity date should match'
                    );
                }
            }
        }
    }

    /**
     * Test Method to test the createTasks() method
     */
    @isTest
    public static void testcreateTasksForEmployeeWithOutUser() {
        Employee testEmployee = [
            SELECT id, EmployeeNumber, UserId, Name
            FROM Employee
            WHERE Email = :TEST_EMAIL_EMPLOYEE_WITHOUT_USER
        ];

        List<CreateOnboardingTasks.RequestInput> requestInputs = new List<CreateOnboardingTasks.RequestInput>();
        CreateOnboardingTasks.RequestInput req = new CreateOnboardingTasks.RequestInput();
        req.selectedTemplates = 'Basic Onboarding';
        req.UserID = testEmployee.UserId;
        requestInputs.add(req);

        Test.startTest();
        List<CreateOnboardingTasks.RequestOutput> requestOutputs = CreateOnboardingTasks.createTasks(
            requestInputs
        );
        Test.stopTest();

        System.assert(!requestOutputs[0].isSuccess);
        System.assert(requestOutputs[0].total_Onboarding_Task == 0);
    }
}