hrservicecenter/force-app/main/default/objects/OnboardingTask__c/OnboardingTask__c.object-meta.xml
<CustomObject>
    <description>This entity represents various onboarding tasks an HR can create for their employees.</description>
    <label>Onboarding Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the task</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTask__c/fields/StartDayOffset__c.field-meta.xml
<CustomField>
    <fullName>StartDayOffset__c</fullName>
    <defaultValue>0</defaultValue>
    <description>This indicates when the employee should begin this onboarding task relative to their start date.</description>
    <label>Start Day Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/OnboardingTemplate__c.object-meta.xml
<CustomObject>
    <description>Custom object that enables an HR agent to create a list of tasks that will help a new employee onboard into the organization.</description>
    <label>Onboarding Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A brief description about the template.</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/OnboardingTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Custom object that represents onboarding tasks that can be associated with a template.</description>
    <label>Onboarding Template Task</label>
    <nameField>
        <displayFormat>OTT-{0000}</displayFormat>
        <label>Template Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTask__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Onboarding Task that is linked to the template</description>
    <label>Onboarding Task</label>
    <referenceTo>OnboardingTask__c</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTemplate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTemplate__c</fullName>
    <description>Parent Template record Id.</description>
    <label>Onboarding Template</label>
    <referenceTo>OnboardingTemplate__c</referenceTo>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/Task/recordTypes/OnboardingTask.recordType-meta.xml
<RecordType>
    <fullName>OnboardingTask</fullName>
    <active>true</active>
    <label>Onboarding Task</label>
</RecordType>

hrservicecenter/force-app/main/default/classes/CreateOnboardingTasks.cls
/**
 * @author  Kunal Parmani
 * @date    5/27/21
 * @description CreateOnboardingTasks class to Initiate Onboarding tasks for Employee.
 * @log
 * -----------------------------------------------------------------------------
 * Date        Developer
 * -----------------------------------------------------------------------------
 * 5/27/21     kunal parmani
 */
public with sharing class CreateOnboardingTasks {
    /**
     * Creates the onboarding tasks for the suplied onboarding templates.
     * @param requestInputs List<RequestInput> representing onboarding templates parameters.
     * @return A List<RequestOutput> representing result.
     */
    @InvocableMethod(
        Label='Create Onboarding Tasks'
        Description='Creates the onboarding tasks for the suplied onboarding templates.'
        Category='Onboarding Tasks'
    )
    public static List<RequestOutput> createTasks(
        List<RequestInput> requestInputs
    ) {
        List<Task> createTaskList = new List<Task>();
        List<Id> OBtaskIdList = new List<Id>();
        List<String> OBtemplateList = new List<String>();
        List<RequestOutput> requestOutputs = new List<RequestOutput>();
        Id recordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName()
            .get('OnboardingTask')
            .getRecordTypeId();

        String OBStr = requestInputs[0].selectedTemplates;
        if (OBStr.contains('; ')) {
            OBStr = OBStr.replaceAll('; ', ';');
        }
        OBtemplateList = OBStr.split(';');

        if (!String.isEmpty(requestInputs[0].UserID)) {
            Employee employeeRecord = EmployeeCtrl.getEmployeeRecordByUserId(
                requestInputs[0].UserID
            )[0];

            for (Task tsk : [
                SELECT id, WhatId
                FROM Task
                WHERE OwnerId = :requestInputs[0].UserID
            ]) {
                if (!OBtaskIdList.contains(tsk.WhatId)) {
                    OBtaskIdList.add(tsk.WhatId);
                }
            }

            for (OnboardingTemplateTask__c OBtemplatetask : [
                SELECT
                    id,
                    OnboardingTask__c,
                    OnboardingTask__r.StartDayOffset__c,
                    OnboardingTask__r.Name,
                    OnboardingTask__r.Description__c
                FROM OnboardingTemplateTask__c
                WHERE OnboardingTemplate__r.Name IN :OBtemplateList
            ]) {
                if (!OBtaskIdList.contains(OBtemplatetask.OnboardingTask__c)) {
                    Task tsk = new Task();
                    Integer daysToAdd = Integer.valueOf(
                        OBtemplatetask.OnboardingTask__r.StartDayOffset__c
                    );

                    if (employeeRecord.StatusAsOf != null) {
                        tsk.ActivityDate = employeeRecord.StatusAsOf.date()
                            .addDays(daysToAdd);
                    } else {
                        tsk.ActivityDate = Date.today().addDays(daysToAdd);
                    }

                    tsk.Subject = OBtemplatetask.OnboardingTask__r.Name;
                    tsk.Description = OBtemplatetask.OnboardingTask__r.Description__c;
                    tsk.WhatId = OBtemplatetask.OnboardingTask__c;
                    tsk.Status = 'Not Started';
                    tsk.OwnerId = requestInputs[0].UserID;
                    tsk.recordtypeId = recordTypeId;

                    OBtaskIdList.add(OBtemplatetask.OnboardingTask__c);
                    createTaskList.add(tsk);
                }
            }

            try {
                insert createTaskList;

                RequestOutput reqOutput = new RequestOutput();
                reqOutput.total_Onboarding_Task = createTaskList.size();
                reqOutput.isSuccess = true;
                requestOutputs.add(reqOutput);
            } catch (Exception e) {
                RequestOutput reqOutput = new RequestOutput();
                reqOutput.total_Onboarding_Task = 0;
                reqOutput.isSuccess = false;
                reqOutput.errorMessage = e.getMessage();
                requestOutputs.add(reqOutput);

                throw new AuraHandledException(
                    'An error occurred while trying to insert employee Onboarding Task data: ' +
                    e.getMessage()
                );
            }
        } else {
            RequestOutput reqOutput = new RequestOutput();
            reqOutput.total_Onboarding_Task = 0;
            reqOutput.isSuccess = false;
            reqOutput.errorMessage = 'Employee does not have a user! Please assign a user to the employee!';
            requestOutputs.add(reqOutput);
        }

        return requestOutputs;
    }

    /**
     * Wrapper class for RequestInput data.
     */
    public class RequestInput {
        @InvocableVariable
        public String selectedTemplates;
        @InvocableVariable
        public String UserID;
    }

    /**
     * Wrapper class for RequestInput data.
     */
    public class RequestOutput {
        @InvocableVariable
        public Boolean isSuccess;
        @InvocableVariable
        public String errorMessage;
        @InvocableVariable
        public Integer total_Onboarding_Task;
    }
}