hrservicecenter/force-app/main/default/objects/OnboardingTask__c/OnboardingTask__c.object-meta.xml
<CustomObject>
    <description>This entity represents various onboarding tasks an HR can create for their employees.</description>
    <label>Onboarding Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplate__c/OnboardingTemplate__c.object-meta.xml
<CustomObject>
    <description>Custom object that enables an HR agent to create a list of tasks that will help a new employee onboard into the organization.</description>
    <label>Onboarding Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/OnboardingTemplateTask__c.object-meta.xml
<CustomObject>
    <description>Custom object that represents onboarding tasks that can be associated with a template.</description>
    <label>Onboarding Template Task</label>
    <nameField>
        <displayFormat>OTT-{0000}</displayFormat>
        <label>Template Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Onboarding Template Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTask__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTask__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Onboarding Task that is linked to the template</description>
    <label>Onboarding Task</label>
    <referenceTo>OnboardingTask__c</referenceTo>
    <relationshipName>Onboarding_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

hrservicecenter/force-app/main/default/objects/OnboardingTemplateTask__c/fields/OnboardingTemplate__c.field-meta.xml
<CustomField>
    <fullName>OnboardingTemplate__c</fullName>
    <description>Parent Template record Id.</description>
    <label>Onboarding Template</label>
    <referenceTo>OnboardingTemplate__c</referenceTo>
    <relationshipName>Template_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

hrservicecenter/force-app/main/default/classes/CheckObjectPermission.cls
public with sharing class CheckObjectPermission {
    public final static String NO_ACCESS_INDICATOR = 'No';
    public final static String YES_ACCESS_INDICATOR = 'Yes';

    /**
     * Checks Object permissions for wkdw__OnboardingTemplate__c,wkdw__OnboardingTemplateTask__c,wkdw__OnboardingTask__c
     * @return A List<RequestOutput> representing result of the API callout.
     */
    @InvocableMethod(
        Label='Check Object Permission'
        Description='Invokes the apex method to check the Object permissions for wkdw__OnboardingTemplate__c,wkdw__OnboardingTemplateTask__c,wkdw__OnboardingTask__c'
        Category='Direct Deposit'
    )
    public static List<RequestOutput> checkObjectsPerm() {
        String errorMessage = '';
        List<RequestOutput> requestOutputs = new List<RequestOutput>();
        RequestOutput requestOutput = new RequestOutput();

        if (!Schema.SObjectType.OnboardingTemplate__c.isAccessible()) {
            requestOutput.hasReadOnboardingTemplate = NO_ACCESS_INDICATOR;
            errorMessage = errorMessage + 'Onboarding Template,';
        }
        if (!Schema.SObjectType.OnboardingTemplateTask__c.isAccessible()) {
            requestOutput.hasReadOnboardingTemplateTask = NO_ACCESS_INDICATOR;
            errorMessage = errorMessage + 'Onboarding Template Task,';
        }
        if (!Schema.SObjectType.OnboardingTask__c.isAccessible()) {
            requestOutput.hasReadOnboardingTask = NO_ACCESS_INDICATOR;
            errorMessage = errorMessage + 'Onboarding Task,';
        }

        if (errorMessage.endsWith(',')) {
            errorMessage = errorMessage.substring(0, errorMessage.length() - 1);
        }

        requestOutput.errorMessage = String.format(
            Label.Object_Permissions_Error_Message,
            new List<String>{ errorMessage }
        );
        requestOutputs.add(requestOutput);

        return requestOutputs;
    }

    /**
     * Wrapper class for RequestOutput data.
     */
    public class RequestOutput {
        @InvocableVariable
        public String hasReadOnboardingTemplate = YES_ACCESS_INDICATOR;
        @InvocableVariable
        public String hasReadOnboardingTemplateTask = YES_ACCESS_INDICATOR;
        @InvocableVariable
        public String hasReadOnboardingTask = YES_ACCESS_INDICATOR;
        @InvocableVariable
        public String errorMessage;
    }
}